import { fetchGroundedPrompt, evaluateRAG, logRAGQueryTelemetry } from './api';

export interface RAGQueryResult {
  answer: string;
  retrievedChunks: Array<{
    id: number;
    title: string;
    content: string;
    similarityScore: number;
    make: string;
    model: string;
    docType: string;
  }>;
  evaluation?: {
    score: number;
    groundednessScore: number;
    citationCount: number;
    retrievedCount: number;
    status: string;
  };
  metrics: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
    estimatedCostUSD: number;
    latencyMs: number;
    modelUsed: string;
  };
}

export async function queryOpenRouter({
  apiKey,
  messages,
  vehicleContext,
  vehicleMake,
  vehicleModel,
  model = 'openai/gpt-4o-mini',
}: {
  apiKey: string;
  messages: Array<{ role: 'user' | 'assistant' | 'system'; content: string }>;
  vehicleContext?: string;
  vehicleMake?: string;
  vehicleModel?: string;
  model?: string;
}): Promise<RAGQueryResult> {
  const startTime = Date.now();
  const lastUserMsg = [...messages].reverse().find((m) => m.role === 'user')?.content || '';

  // 1. Retrieve RAG grounded system prompt & vector chunks from backend
  let groundedData = await fetchGroundedPrompt(lastUserMsg, vehicleMake, vehicleModel, vehicleContext);

  let systemPrompt = `You are AuraOS AI Diagnostic Engine, an advanced automotive diagnostic assistant integrated into AuraAutomotiveOS.
${vehicleContext ? `Active Vehicle Loaded: ${vehicleContext}` : ''}
Your knowledge encompasses OEM service manuals, Diagnostic Trouble Codes (DTCs), wiring circuit pin-outs, torque specifications, component testing procedures, and NHTSA recall bulletins.
Provide accurate, professional, step-by-step automotive service advice. Use clear markdown formatting, bullet points, and bold headers where appropriate. If asked about non-automotive topics, politely decline and remind the user that AuraOS is dedicated strictly to vehicle service intelligence.`;

  let retrievedChunks: any[] = [];
  if (groundedData && groundedData.systemPrompt) {
    systemPrompt = groundedData.systemPrompt;
    retrievedChunks = groundedData.retrievedChunks || [];
  }

  // Sliding window context history (keep system + last 8 messages)
  const windowedMessages = messages.slice(-8);
  const payloadMessages = [
    { role: 'system', content: systemPrompt },
    ...windowedMessages.map((m) => ({ role: m.role, content: m.content })),
  ];

  const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey.trim()}`,
      'HTTP-Referer': typeof window !== 'undefined' ? window.location.origin : 'http://localhost:4173',
      'X-Title': 'AuraAutomotiveOS Diagnostic Engine',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: model,
      messages: payloadMessages,
      temperature: 0.2,
      max_tokens: 1000,
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`OpenRouter API error (${response.status}): ${errorText}`);
  }

  const data = await response.json();
  const answer = data.choices?.[0]?.message?.content;
  if (!answer) {
    throw new Error('No response generated by OpenRouter');
  }

  const latencyMs = Date.now() - startTime;

  // Extract usage telemetry
  const promptTokens = data.usage?.prompt_tokens || Math.ceil(JSON.stringify(payloadMessages).length / 4);
  const completionTokens = data.usage?.completion_tokens || Math.ceil(answer.length / 4);
  const totalTokens = promptTokens + completionTokens;

  // Approximate cost
  const pCost = (promptTokens / 1000) * 0.00015;
  const cCost = (completionTokens / 1000) * 0.0006;
  const estimatedCostUSD = Number((pCost + cCost).toFixed(6));

  // Run RAG answer evaluation
  const evaluation = await evaluateRAG(lastUserMsg, answer, retrievedChunks);

  // Log query telemetry to SQLite database asynchronously
  const topSim = retrievedChunks.length > 0 ? retrievedChunks[0].similarityScore || 0.9 : 0.0;
  logRAGQueryTelemetry({
    query: lastUserMsg,
    retrievedCount: retrievedChunks.length,
    topSimilarity: topSim,
    promptTokens,
    completionTokens,
    modelName: model,
    latencyMs,
  });

  return {
    answer,
    retrievedChunks,
    evaluation: evaluation || undefined,
    metrics: {
      promptTokens,
      completionTokens,
      totalTokens,
      estimatedCostUSD,
      latencyMs,
      modelUsed: model,
    },
  };
}
